basePath: /sweet/admin
definitions:
  sweet-cms_form_response.Response:
    properties:
      data: {}
      error_code:
        type: integer
      error_message:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
info:
  contact:
    email: maxdwy@gmail.com
    name: 南
  description: 基于gin+gorm的后台管理项目，实现部分低代码
  title: 试验性项目
  version: "0.1"
paths:
  /dict/code/{code}:
    get:
      description: 根据CODE获取字典详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 字典CODE
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/sweet-cms_form_response.Response'
      summary: 字典详情
      tags:
      - 字典
  /dict/id/{id}:
    get:
      description: 根据ID获取字典详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 字典ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/sweet-cms_form_response.Response'
      summary: 字典详情
      tags:
      - 字典
swagger: "2.0"
